; PlatformIO Project Configuration File for Teensy 4.x LED Blinker
;
;   Build:    pio run
;   Upload:   pio run -t upload
;   Monitor:  pio device monitor

[platformio]
default_envs = teensy41

[env]
platform = teensy
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200

[env:teensy41]
board = teensy41

[env:teensy40]
board = teensy40
