; PlatformIO Project Configuration File for Teensy 4.1 HID Multiplexer

[platformio]
default_envs = teensy41

[env]
platform = teensy
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200

[env:teensy41]
board = teensy41
build_flags = 
    -DUSB_SERIAL_HID
